import {
  MemberBusiness,
  ChamberEvent,
  ChamberNews,
  JobListing,
  ContactSubmission,
  BusinessReview,
  ImpactStory,
  CommitteeLeader,
} from '@/types';

export const SEED_CATEGORIES = [
  { id: 'cat-1', name: 'Manufacturing', icon: '🏭', desc: 'Heavy industry, FMCG, packaging & fabrication' },
  { id: 'cat-2', name: 'Wholesale', icon: '🏬', desc: 'B2B bulk trading, agricultural commodities & commodities' },
  { id: 'cat-3', name: 'Retail', icon: '🛍️', desc: 'Showrooms, jewellery, fashion, electronics & supermarkets' },
  { id: 'cat-4', name: 'Professional', icon: '💼', desc: 'Chartered Accountants, legal advocates, tax & architects' },
  { id: 'cat-5', name: 'Service Provider', icon: '🔧', desc: 'Healthcare, hospitals, IT, logistics, hospitality' },
  { id: 'cat-6', name: 'Distribution', icon: '🚛', desc: 'Supply chain networks, FMCG distribution & dealerships' },
  { id: 'cat-7', name: 'Import / Export', icon: '🌐', desc: 'Cross-border trade, agri-exports & raw materials' },
];

export const SEED_INDUSTRIES = [
  { id: 'ind-1', name: 'Food Processing & FMCG', icon: '🍽️', category: 'Manufacturing', imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=600&q=80' },
  { id: 'ind-2', name: 'Textile & Garments', icon: '🧵', category: 'Manufacturing', imageUrl: 'https://images.unsplash.com/photo-1579298245158-33e8f568f7d3?auto=format&fit=crop&w=600&q=80' },
  { id: 'ind-3', name: 'Jewellery & Precious Metals', icon: '💎', category: 'Retail', imageUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=600&q=80' },
  { id: 'ind-4', name: 'Agricultural Commodities', icon: '🌾', category: 'Wholesale', imageUrl: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=600&q=80' },
  { id: 'ind-5', name: 'Hospitals & Healthcare', icon: '🏥', category: 'Service Provider', imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=600&q=80' },
  { id: 'ind-6', name: 'Hotels & Hospitality', icon: '🏨', category: 'Service Provider', imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80' },
  { id: 'ind-7', name: 'Transporters & Logistics', icon: '🚛', category: 'Distribution', imageUrl: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?auto=format&fit=crop&w=600&q=80' },
  { id: 'ind-8', name: 'Chartered Accountants & Audit', icon: '📊', category: 'Professional', imageUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=600&q=80' },
  { id: 'ind-9', name: 'Software Development & IT', icon: '💻', category: 'Professional', imageUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=600&q=80' },
  { id: 'ind-10', name: 'Advocates & Law Firms', icon: '⚖️', category: 'Professional', imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80' },
  { id: 'ind-11', name: 'Real Estate & Infrastructure', icon: '🏗️', category: 'Manufacturing', imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=600&q=80' },
  { id: 'ind-12', name: 'Automobile Dealers & Parts', icon: '🚗', category: 'Retail', imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=80' },
  { id: 'ind-13', name: 'Steel & Hardware Trading', icon: '🔩', category: 'Wholesale', imageUrl: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=600&q=80' },
  { id: 'ind-14', name: 'Coaching & Higher Education', icon: '📚', category: 'Service Provider', imageUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=600&q=80' },
  { id: 'ind-15', name: 'Event Management & Media', icon: '🎭', category: 'Service Provider', imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=600&q=80' },
  { id: 'ind-16', name: 'Electronics & Home Appliances', icon: '📱', category: 'Retail', imageUrl: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=600&q=80' },
];

export const SEED_MEMBERS: MemberBusiness[] = [
  {
    id: 'VND_1785762656744_88',
    businessName: 'Better Foods India',
    legalName: 'Better Foods & Beverage Industries Pvt. Ltd.',
    ownerName: 'Sudhi Agrawal',
    category: 'Manufacturing',
    industry: 'Food Processing & FMCG',
    description: 'Premier manufacturer and wholesale distributor of processed agro-foods, organic snack foods, and bakery essentials serving central India.',
    detailed: 'Established with a focus on hygiene and modern automation, Better Foods India processes quality grains, specialty confectionery, and ready-to-cook food products. Equipped with state-of-the-art cold storage and testing labs in Jabalpur.',
    tagline: 'Purity in Every Grain, Trust in Every Pack',
    phone: '+91 8319565363',
    whatsapp: '918319565363',
    email: 'contact@betterfoods.in',
    website: 'https://betterfoods.in',
    social: 'https://linkedin.com/company/better-foods',
    address: 'Plot 42, Richhai Industrial Area, Phase-II',
    city: 'Jabalpur',
    pinCode: '482010',
    maps: 'https://maps.google.com/?q=Richhai+Industrial+Area+Jabalpur',
    timing: 'Mon–Sat: 09:30 AM – 07:00 PM',
    gst: '23AABCB1234F1Z9',
    estYear: '2014',
    employees: '48',
    services: 'Bulk Food Supply, Contract Manufacturing, Private Label Packaging',
    products: 'Wheat Flour, Bakery Premixes, Roasted Snacks, Extruded Foods',
    awards: 'MP MSME Excellence Award 2023, ISO 22000 Certified',
    plan: 'Premium',
    status: 'approved',
    featured: true,
    rating: 4.9,
    reviewCount: 28,
    workPhotos: [
      'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    ],
    logoUrl: '',
    joinedAt: '2023-01-15',
  },
  {
    id: 'VND_102',
    businessName: 'Agrawal Jewellers & Sons',
    legalName: 'Shree Agrasen Jewellers LLP',
    ownerName: 'Ramesh Chandra Agrawal',
    category: 'Retail',
    industry: 'Jewellery & Precious Metals',
    description: 'Heritage jewellers known for BIS 916 Hallmarked bridal gold, certified conflict-free diamonds, and bespoke heirloom Kundan jewellery.',
    detailed: 'Spanning three generations of craftsmanship in the heart of Jabalpur, Agrawal Jewellers has adorned weddings across Madhya Pradesh for over 45 years with an unmatched legacy of purity.',
    tagline: 'Adorning Generations with Timeless Purity',
    phone: '+91 9425154321',
    whatsapp: '919425154321',
    email: 'info@agrawaljewellersjbp.com',
    website: 'https://agrawaljewellersjbp.com',
    social: 'https://instagram.com/agrawaljewellers_jbp',
    address: 'Bada Fuhara, Lordganj Market',
    city: 'Jabalpur',
    pinCode: '482002',
    maps: 'https://maps.google.com/?q=Bada+Fuhara+Jabalpur',
    timing: 'Mon–Sat: 11:00 AM – 08:30 PM',
    gst: '23AAACA9876K1ZY',
    estYear: '1979',
    employees: '26',
    services: 'Custom Gold Designing, Diamond Certification, Jewellery Valuation',
    products: 'Bridal Sets, Kundan Necklaces, Solitaire Rings, Temple Jewellery',
    awards: 'All India Gem & Jewellery Council Trusted Jeweller 2022',
    plan: 'Premium',
    status: 'approved',
    featured: true,
    rating: 4.8,
    reviewCount: 42,
    workPhotos: [
      'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80',
    ],
    logoUrl: '',
    joinedAt: '2022-04-10',
  },
  {
    id: 'VND_103',
    businessName: 'Narmada Logistics & Warehousing',
    legalName: 'Narmada Fleet & Freight Carriers',
    ownerName: 'Vikas Agrawal',
    category: 'Distribution',
    industry: 'Transporters & Logistics',
    description: 'Comprehensive road transportation, containerized freight fleets, and modern palletized warehousing spanning Central India.',
    detailed: 'With a dedicated fleet of 110+ GPS-tracked trucks, temperature-controlled trailers, and 150,000 sq.ft of dry warehousing, Narmada Logistics guarantees seamless pan-India connectivity.',
    tagline: 'Connecting Central India to the Nation',
    phone: '+91 9826134567',
    whatsapp: '919826134567',
    email: 'dispatch@narmadalogistics.co.in',
    website: 'https://narmadalogistics.co.in',
    address: 'Transport Nagar, Karmeta Bypass Road',
    city: 'Jabalpur',
    pinCode: '482003',
    maps: 'https://maps.google.com/?q=Transport+Nagar+Jabalpur',
    timing: '24/7 Operations',
    gst: '23AACCN4512L1ZX',
    estYear: '2008',
    employees: '85',
    services: 'Full Truck Load (FTL), Parcel Delivery, 3PL Warehousing, Reefer Transport',
    products: 'Fleet Management Solutions, Bonded Cargo Handlers',
    awards: 'Best Transporter Award MP Chamber 2021',
    plan: 'Pro',
    status: 'approved',
    featured: true,
    rating: 4.7,
    reviewCount: 19,
    workPhotos: [
      'https://images.unsplash.com/photo-1519003722824-194d4455a60c?auto=format&fit=crop&w=800&q=80',
    ],
    logoUrl: '',
    joinedAt: '2022-08-19',
  },
  {
    id: 'VND_104',
    businessName: 'Agrawal & Associates, Chartered Accountants',
    legalName: 'Agrawal & Associates LLP',
    ownerName: 'CA Piyush Agrawal, FCA, DISA',
    category: 'Professional',
    industry: 'Chartered Accountants & Audit',
    description: 'Statutory audits, corporate tax planning, GST litigation, project finance syndication, and company law compliance for MSMEs and corporate enterprises.',
    detailed: 'A 4-partner firm with over 25 years of institutional advisory experience helping manufacturing and trading enterprises maintain impeccable compliance and optimize capital structure.',
    tagline: 'Precision in Finance, Integrity in Counsel',
    phone: '+91 7612401890',
    whatsapp: '919425801234',
    email: 'piyush@agrawalca.in',
    website: 'https://agrawalca.in',
    address: '402, Samdariya Mall Complex, Civic Centre',
    city: 'Jabalpur',
    pinCode: '482001',
    maps: 'https://maps.google.com/?q=Samdariya+Mall+Jabalpur',
    timing: 'Mon–Sat: 10:00 AM – 07:30 PM',
    gst: '23AACFA8921R1ZQ',
    estYear: '1998',
    employees: '18',
    services: 'Statutory Audit, GST Advisory, Income Tax Tribunals, Corporate Restructuring',
    products: 'Project DPRs, Valuation Certificates, Transfer Pricing Studies',
    awards: 'ICAI Central Region Commendation 2019',
    plan: 'Pro',
    status: 'approved',
    featured: true,
    rating: 4.9,
    reviewCount: 34,
    workPhotos: [],
    logoUrl: '',
    joinedAt: '2022-01-11',
  },
  {
    id: 'VND_105',
    businessName: 'Mahakoshal Agro Commodities',
    legalName: 'Mahakoshal Agro Trading Corporation',
    ownerName: 'Sanjay Agrawal & Deepak Agrawal',
    category: 'Wholesale',
    industry: 'Agricultural Commodities',
    description: 'Leading mandiship and bulk brokerage in premium Sharbati wheat, pulses, soybean seed, and mustard oil cakes across Madhya Pradesh.',
    detailed: 'Connecting farmers and large processing mills with daily transparent trade facilitation in Krishi Upaj Mandi Jabalpur and Katni.',
    tagline: 'Bridging Mandis to Mega-Processors',
    phone: '+91 9425112233',
    whatsapp: '919425112233',
    email: 'trade@mahakoshalagro.com',
    address: 'Shop 14-16, Krishi Upaj Mandi, Vijay Nagar',
    city: 'Jabalpur',
    pinCode: '482002',
    maps: 'https://maps.google.com/?q=Krishi+Upaj+Mandi+Jabalpur',
    timing: 'Mon–Sat: 08:30 AM – 06:30 PM',
    gst: '23AADCM7621N1ZM',
    estYear: '1995',
    employees: '22',
    services: 'Mandi Commission Agency, Warehousing Receipts Financing, Grain Grading',
    products: 'MP Sharbati Wheat, Chana Dal, Soybean, Mustard Cake',
    awards: 'Top Mandi Trader Award 2022',
    plan: 'Pro',
    status: 'approved',
    featured: false,
    rating: 4.6,
    reviewCount: 15,
    workPhotos: [],
    logoUrl: '',
    joinedAt: '2023-03-01',
  },
  {
    id: 'VND_106',
    businessName: 'Sanskar Valley Hospital & Trauma Centre',
    legalName: 'Sanskar Valley Healthcare Ltd.',
    ownerName: 'Dr. Alok Agrawal, MS, MCh (Ortho)',
    category: 'Service Provider',
    industry: 'Hospitals & Healthcare',
    description: '150-bed multi-superspeciality hospital with round-the-clock emergency ICU, cardiac catheterization laboratory, joint replacement, and advanced diagnostics.',
    detailed: 'Equipped with NABH accreditation, modular laminar air flow operation theatres, and dedicated concessional healthcare desks for community elders and disadvantaged families.',
    tagline: 'Clinical Excellence, Compassionate Healing',
    phone: '+91 7614056789',
    whatsapp: '917614056789',
    email: 'info@sanskarvalleyhospital.org',
    website: 'https://sanskarvalleyhospital.org',
    address: 'Near Wright Town Stadium, Wright Town',
    city: 'Jabalpur',
    pinCode: '482002',
    maps: 'https://maps.google.com/?q=Wright+Town+Jabalpur',
    timing: 'Emergency: 24/7 | OPD: 09:00 AM – 08:00 PM',
    gst: '23AABCS4490P1ZL',
    estYear: '2011',
    employees: '160',
    services: 'Joint Replacement, Trauma Care, Cardiology, Laparoscopy, Neonatal ICU',
    products: 'Executive Health Checkups, Home Care Services',
    awards: 'NABH Accredited Multi-Speciality Hospital',
    plan: 'Premium',
    status: 'approved',
    featured: true,
    rating: 4.9,
    reviewCount: 57,
    workPhotos: [
      'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80',
    ],
    logoUrl: '',
    joinedAt: '2022-06-05',
  },
];

export const SEED_EVENTS: ChamberEvent[] = [
  {
    id: 'EV_2026_01',
    title: 'ACCI Annual Central India Business Conclave 2026',
    slug: 'acci-annual-central-india-business-conclave-2026',
    category: 'Business Networking',
    date: '2026-10-18',
    time: '09:30 AM – 06:00 PM',
    venue: 'Hotel Satkar Grande & Convention Centre, Civic Centre, Jabalpur',
    description: 'The flagship business gathering uniting 600+ industrial leaders, MSME founders, and policymakers. Featuring keynote dialogues on the MP Industrial Policy, tax incentives, export corridors, and next-generation family business succession.',
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
    bgColor: 'linear-gradient(135deg, #07174a, #1540a8)',
    registrationUrl: '/membership',
    status: 'upcoming',
    createdAt: '2026-08-10',
  },
  {
    id: 'EV_2026_02',
    title: 'MSME GST Compliance & Direct Tax Dispute Resolution Workshop',
    slug: 'msme-gst-compliance-workshop-2026',
    category: 'Seminar',
    date: '2026-09-27',
    time: '03:00 PM – 07:00 PM',
    venue: 'ACCI Chamber Secretariat Hall, Napier Town, Jabalpur',
    description: 'Interactive clinic with senior tax attorneys and GST departmental officials covering e-invoicing revisions, input tax credit audits, and Section 43B(h) vendor payment provisions for micro and small enterprises.',
    imageUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=80',
    bgColor: 'linear-gradient(135deg, #166534, #052e16)',
    registrationUrl: '/contact',
    status: 'upcoming',
    createdAt: '2026-08-20',
  },
  {
    id: 'EV_2026_03',
    title: 'Maharaja Agrasen Jayanti Trade Fair & Heritage Expo',
    slug: 'maharaja-agrasen-jayanti-trade-fair-2026',
    category: 'Cultural & Trade',
    date: '2026-10-12',
    time: '11:00 AM – 10:00 PM',
    venue: 'Golbazar Exhibition Grounds, Gorakhpur, Jabalpur',
    description: 'A 3-day community and trade showcase displaying products from 150+ Agrawal artisans, jewellers, textile houses, and food manufacturers with cultural evening programs honoring community stalwarts.',
    imageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80',
    bgColor: 'linear-gradient(135deg, #b45309, #78350f)',
    registrationUrl: '/membership',
    status: 'upcoming',
    createdAt: '2026-08-01',
  },
];

export const SEED_NEWS: ChamberNews[] = [
  {
    id: 'NEWS_101',
    title: 'ACCI Delegation Meets MP Industries Minister to Fast-Track Jabalpur Industrial Corridor',
    slug: 'acci-delegation-meets-mp-industries-minister-jabalpur-corridor',
    category: 'Chamber Circular',
    excerpt: 'Delegation led by President submits memorandum advocating for dedicated multi-modal logistics hub and concessional power tariffs for manufacturing units.',
    content: `A high-level executive delegation representing the Agrawal Chamber of Commerce & Industries (ACCI) Jabalpur met with the Hon'ble Minister for Industrial Policy & Investment Promotion at the Secretariat in Bhopal.

The delegation placed on record key representations from over 350 local manufacturing and processing units:
1. Fast-tracking the Jabalpur–Nagpur industrial spur connectivity.
2. Rationalization of local municipal stamp duty on industrial plot leases.
3. Creation of a dedicated 200-acre food processing cluster in Richhai with automated cold-chain logistics.

The Minister praised ACCI for its proactive role in private sector employment generation in Mahakoshal and assured phased implementation within the current financial quarter.`,
    imageUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=1200&q=80',
    author: 'Secretariat, ACCI Jabalpur',
    publishedAt: '2026-08-28',
    status: 'published',
  },
  {
    id: 'NEWS_102',
    title: 'Trade Advisory: Revised Compliance Timelines for MSME Vendor Payments',
    slug: 'trade-advisory-revised-compliance-timelines-msme-payments',
    category: 'Trade Advisory',
    excerpt: 'Detailed analysis and guidelines issued by the ACCI Legal & Taxation Committee on recent statutory clarifications.',
    content: `The Taxation Committee of ACCI has prepared an advisory circular to assist chamber members with accurate bookkeeping and compliance regarding trade payables to micro and small enterprises.

Members are urged to verify the Udyam Registration certificates of all vendors and adhere to agreed credit horizons to avoid statutory disallowances. A dedicated help desk is open at the Chamber Secretariat every Wednesday and Saturday.`,
    imageUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=1200&q=80',
    author: 'ACCI Tax & Legal Committee',
    publishedAt: '2026-08-15',
    status: 'published',
  },
  {
    id: 'NEWS_103',
    title: 'Launch of ACCI Youth Entrepreneurship & Digital Mentorship Cell',
    slug: 'launch-of-acci-youth-entrepreneurship-mentorship-cell',
    category: 'Community Achievement',
    excerpt: 'New initiative designed to mentor 100+ first-generation Agrawal founders in e-commerce, modern branding, and debt/equity capital.',
    content: `Recognizing the rapid digital transformation of traditional trading houses, ACCI has inaugurated its Youth Entrepreneurship Cell. The cell pairs seasoned industrial captains with younger entrepreneurs in retail, software, and agro-value chains.

Applications for the first cohort are now open through the Member Portal.`,
    imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80',
    author: 'Youth Wing, ACCI',
    publishedAt: '2026-07-29',
    status: 'published',
  },
];

export const SEED_JOBS: JobListing[] = [
  {
    id: 'JOB_01',
    company: 'Better Foods India',
    title: 'Senior Accountant & Tally ERP Lead',
    category: 'Accounting & Finance',
    jobType: 'Full-Time',
    urgency: 'Urgent',
    salary: '₹28,000 – ₹38,000 / month',
    location: 'Richhai Industrial Area, Jabalpur',
    description: 'Looking for an experienced accountant well-versed in Tally Prime, GST GSTR-1/3B filing, inventory reconciliations, and supplier payments.',
    skills: 'Tally Prime, GST Filing, TDS, Bank Reconciliation, MS Excel',
    contactEmail: 'hr@betterfoods.in',
    contactWhatsApp: '918319565363',
    status: 'Active',
    postedAt: '2026-08-30',
  },
  {
    id: 'JOB_02',
    company: 'Agrawal Jewellers & Sons',
    title: 'Showroom Sales Executive & Bridal Jewellery Consultant',
    category: 'Sales & Marketing',
    jobType: 'Full-Time',
    urgency: 'Open',
    salary: '₹20,000 – ₹30,000 / month + Incentives',
    location: 'Bada Fuhara, Lordganj, Jabalpur',
    description: 'Responsible for attending retail walk-in bridal clients, diamond piece demonstrations, order coordination, and maintaining customer rapport.',
    skills: 'Retail Sales, Customer Relationship, Hindi & English Fluency, Jewellery Knowledge',
    contactEmail: 'careers@agrawaljewellersjbp.com',
    contactWhatsApp: '919425154321',
    status: 'Active',
    postedAt: '2026-08-25',
  },
  {
    id: 'JOB_03',
    company: 'Narmada Logistics & Warehousing',
    title: 'Warehouse Operations Supervisor',
    category: 'Operations',
    jobType: 'Full-Time',
    urgency: 'Urgent',
    salary: '₹22,000 – ₹28,000 / month',
    location: 'Transport Nagar, Karmeta, Jabalpur',
    description: 'Supervising dispatch loading, fleet arrival tracking, stock auditing, and dispatch manifests for FMCG consignments.',
    skills: 'Logistics Coordination, Inventory Auditing, Team Supervision',
    contactEmail: 'dispatch@narmadalogistics.co.in',
    contactWhatsApp: '919826134567',
    status: 'Active',
    postedAt: '2026-08-27',
  },
];

export const SEED_LEADERSHIP: CommitteeLeader[] = [
  {
    id: 'LDR_01',
    name: 'Shri Sudhi Agrawal',
    designation: 'Patron & Convener',
    organization: 'Better Foods & Beverage Industries',
    category: 'Office Bearer',
    bio: 'Pioneering agro-processing industrialist dedicated to institutional transparency, digital modernization, and mutual prosperity across Mahakoshal.',
    phone: '+91 8319565363',
    email: 'accijabalpur@gmail.com',
  },
  {
    id: 'LDR_02',
    name: 'Shri Ramesh Chandra Agrawal',
    designation: 'President',
    organization: 'Shree Agrasen Jewellers',
    category: 'Office Bearer',
    bio: 'Respected senior merchant with four decades of service to community institutions and business arbitration in Jabalpur.',
  },
  {
    id: 'LDR_03',
    name: 'CA Piyush Agrawal, FCA',
    designation: 'General Secretary',
    organization: 'Agrawal & Associates Chartered Accountants',
    category: 'Office Bearer',
    bio: 'Chartered Accountant guiding Chamber policy, MSME compliance facilitation, and government representations.',
  },
  {
    id: 'LDR_04',
    name: 'Shri Vikas Agrawal',
    designation: 'Treasurer & Chapter Lead (Logistics)',
    organization: 'Narmada Fleet & Freight Carriers',
    category: 'Office Bearer',
    bio: 'Oversees financial accountability and freight trade expansion initiatives.',
  },
  {
    id: 'LDR_05',
    name: 'Dr. Alok Agrawal, MS (Ortho)',
    designation: 'Executive Council Member (Healthcare & Welfare)',
    organization: 'Sanskar Valley Multi-Speciality Hospital',
    category: 'Executive Committee',
    bio: 'Leads community health clinics, medical aid endowments, and healthcare entrepreneurship.',
  },
  {
    id: 'LDR_06',
    name: 'Shri Sanjay Agrawal',
    designation: 'Executive Council Member (Mandi & Wholesale)',
    organization: 'Mahakoshal Agro Trading Corporation',
    category: 'Executive Committee',
    bio: 'Veteran mandiship operator championing fair pricing and grower–processor contracts.',
  },
];

export const SEED_IMPACT_STORIES: ImpactStory[] = [
  {
    id: 'STORY_01',
    title: 'From a Small Shop to a Regional FMCG Supplier',
    authorName: 'Sudhi Agrawal',
    businessName: 'Better Foods India',
    story: 'ACCI provided our business with the peer network, credible buyer introductions, and bank finance syndication needed to expand from local trading to an automated manufacturing facility employing nearly fifty people.',
    status: 'approved',
    createdAt: '2026-05-10',
  },
  {
    id: 'STORY_02',
    title: 'Resolving Supply Chain Roadblocks Through Chamber Alliances',
    authorName: 'Vikas Agrawal',
    businessName: 'Narmada Logistics',
    story: 'During nationwide supply crunches, the institutional backing of ACCI enabled us to coordinate reciprocal return-load partnerships with traders across Chhattisgarh and Maharashtra, cutting transit costs by 22%.',
    status: 'approved',
    createdAt: '2026-06-22',
  },
];

export const SEED_REVIEWS: BusinessReview[] = [
  {
    id: 'REV_01',
    vendorId: 'VND_1785762656744_88',
    businessName: 'Better Foods India',
    reviewerName: 'Manish Goyal',
    rating: 5,
    reviewText: 'Exceptional product quality and consistent delivery timelines. One of the most dependable food manufacturers in MP.',
    status: 'approved',
    createdAt: '2026-08-12',
  },
  {
    id: 'REV_02',
    vendorId: 'VND_102',
    businessName: 'Agrawal Jewellers & Sons',
    reviewerName: 'Sunita Agrawal',
    rating: 5,
    reviewText: 'Bought our daughter bridal jewellery here. Impeccable craftsmanship, complete hallmarking transparency, and warm family service.',
    status: 'approved',
    createdAt: '2026-07-30',
  },
];

export interface GalleryAlbum {
  id: string;
  title: string;
  category: string;
  date: string;
  coverUrl: string;
  photoCount: number;
  description: string;
}

export const SEED_GALLERY: GalleryAlbum[] = [
  {
    id: 'GAL_01',
    title: 'Central India Business Conclave & Industrial Awards',
    category: 'Trade Summit',
    date: 'Hotel Satkar Grand, Jabalpur',
    coverUrl: '/images/conclave_hero.jpg',
    photoCount: 42,
    description: 'Inaugural addresses by industry captains, MSME policy releases, and felicitation of senior community stalwarts.',
  },
  {
    id: 'GAL_02',
    title: 'Maharaja Agrasen Jayanti Trade & Heritage Exhibition',
    category: 'Cultural & Trade',
    date: 'Golbazar Exhibition Grounds',
    coverUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80',
    photoCount: 65,
    description: 'B2B pavilion displays featuring 150+ Agrawal manufacturers, jewellers, and artisans from across Mahakoshal.',
  },
  {
    id: 'GAL_03',
    title: 'Executive Delegation at MP State Industrial Ministry',
    category: 'Policy Delegation',
    date: 'Vallabh Bhavan, Bhopal',
    coverUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80',
    photoCount: 18,
    description: 'Joint memorandum submitted by ACCI President and Office Bearers advocating for Jabalpur logistics hub.',
  },
  {
    id: 'GAL_04',
    title: 'Youth Entrepreneurship & E-Commerce Roundtable',
    category: 'Youth Wing',
    date: 'Chamber Secretariat Hall',
    coverUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80',
    photoCount: 24,
    description: 'Mentorship clinic connecting next-generation founders with seasoned exporters and venture financiers.',
  },
];
